### ISSUE TITLE
前端相关

### ISSUE THREAD

**Issue by SuiYunsy** [MrGreyfun/Local-Code-Interpreter#2]
最新版在我这里不会渲染代码了，会挤成一团😂
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/fc578877-fea1-4bf7-9d61-fa7d26226611)

**Comment by SuiYunsy** [comment]
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/428c98aa-8085-43d8-93c4-38c8f4c5336f)
没开脚本的完整截图

**Comment by MrGreyfun** [comment]
请确保你的gradio版本是3.39.0，老版本的ChatBot确实有一些问题，3.39.0可能要求Python 3.8及以上

**Comment by SuiYunsy** [comment]
> 请确保你的gradio版本是3.39.0，老版本的ChatBot确实有一些问题，3.39.0可能要求Python 3.8及以上

受教了！非常感谢，更新就没问题啦
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/8e0a7f16-7af0-4b43-86de-85de6cb78639)
