### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by SuiYunsy** [MrGreyfun/Local-Code-Interpreter#3]
在问这个问题（来源：https://github.com/zots0127/ChatGPT-Code-Interpreter-Examples）时：
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/e5e883f6-bc28-42c5-8a5c-dfde698d77d4)

运行到最后总是遇到这样的问题：
cmd里：
PermissionError: [Errno 13] Permission denied: 'cache/work_dir_1276374917328\\unzipped_files'
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/a635ac84-49dc-483c-b22c-5b574ca4470f)
页面上：
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/1e080e59-cfb2-4641-ad5f-6dde82198b4a)

我是Windows10，已经用管理员权限执行python web_ui.py了，对这个cache文件夹也设置了Everyone的权限：
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/1ad6f092-d443-467f-8e44-8dee0c354247)

实在不知道哪里出了什么问题，求助大佬~

**Comment by SuiYunsy** [comment]
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/639a7aca-3c88-47ad-90dd-63587a25974a)
甚至图都出来了，填入列名时又被“拒绝权限”😂

**Comment by MrGreyfun** [comment]
看上去是路径不对，请提供完整问题、发送的文件及生成的代码

**Comment by SuiYunsy** [comment]
> 看上去是路径不对，请提供完整问题、发送的文件及生成的代码

抱歉大佬，最后是key的原因😂换了一个key最终成果就正常了
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/6c7f2eec-ee17-4219-a41e-ef7e1fb57ac8)

**Comment by SuiYunsy** [comment]
![gdp_animation](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/104718844/83dbec86-4b70-462b-99b2-60202acb4219)
真的牛啊，3.5的key也可以做到生成gif
