### ISSUE TITLE
给定了两个列表，打算尝试一下可视化输出图片，为什么输出不了图片？

### ISSUE THREAD

**Issue by zxjhellow2** [MrGreyfun/Local-Code-Interpreter#47]
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/61675023/8d4358db-bfb6-425e-be6a-eb6942520d45) 也没有改变哪个地方

**Comment by MrGreyfun** [comment]
看上去没有问题，检查一下cache目录下的temp文件夹里面有没有图片文件

**Comment by zxjhellow2** [comment]
看了一下 有的 这种情况怎么在前端显示呀？

**Comment by MrGreyfun** [comment]
正常情况下是会显示的，这个bug我没有遇到过，也没法复现，可能是由于gradio版本的问题？建议使用readme相同的Python和gradio版本试试，也可以dubug看一下web_ui.py的history变量，观察在执行完输出图片的代码后，history列表里有没有添加图片消息

**Comment by MrGreyfun** [comment]
正常情况下是会显示的，这个bug我没有遇到过，也没法复现，可能是由于gradio版本的问题？建议使用readme相同的Python和gradio版本试试，也可以dubug看一下web_ui.py的history变量，观察在执行完输出图片的代码后，history列表里有没有添加图片消息

**Comment by zxjhellow2** [comment]
好的 我再debug一下 谢谢

**Comment by zxjhellow2** [comment]
大佬，刚刚我仔细检查了一遍，理解错意思了，发现cache里面只有work开头的文件夹，并么有temp开头的文件夹，但是work开头的文件夹里有生成的图片

**Comment by zxjhellow2** [comment]
大概是线程被占用的原因，但是我现在仍然没有搞好这个bug，导致不能写入图片 
 OSError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。

**Comment by zxjhellow2** [comment]
在写入图片的函数（下图代码）之前，出现了一个错误  ConnectionResetError: [WinError 995] 由于线程退出或应用程序请求，已中止 I/O 操作。
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/61675023/f976180f-e95f-4e50-8668-c6e4f7cc0ea3) 大概是这个错误的原因，还没有修好

**Comment by zxjhellow2** [comment]
![image](https://github.com/MrGreyfun/Local-Code-Interpreter/assets/61675023/cf08888d-826d-43d4-99c7-67046e8e56a9)

**Comment by cn19** [comment]
不调试的时候也报这个错误么，有没有可能是debug时间太长，前端断开了后端的连接。

**Comment by zxjhellow2** [comment]
> 不调试的时候也报这个错误么，有没有可能是debug时间太长，前端断开了后端的连接。

直接运行的时候也是出现 [WinError 995] 这个错误，换了环境就运行成功了，总怀疑是我电脑环境的问题，也不太懂这块
