### ISSUE TITLE
会支持使用网页端cookie吗？

### ISSUE THREAD

**Issue by LINKlang** [MrGreyfun/Local-Code-Interpreter#8]
比如说https://github.com/chatanywhere/GPT_API_free
这个里面的apikey
还有会支持使用网页端cookie使用吗

**Comment by LINKlang** [comment]
啊找到了baseurl了

**Comment by zh3305** [comment]
https://github.com/chatanywhere/GPT_API_free 的话更改baseurl就可以使用了
